{"uid":"7d8a6e2433756b56","name":"Тест: выход из аккаунта","fullName":"tests.personal_account_test.TestRestorePassword#test_logout","historyId":"2327d1e2f6d63044792a4617579497ef","time":{"start":1734771054957,"stop":1734771054958,"duration":1},"status":"broken","statusMessage":"TypeError: 'generator' object is not callable","statusTrace":"self = <personal_account_test.TestRestorePassword object at 0x0000014F9C6EB490>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"3cf13f068ec8a992cb22ee7148588ffd\")>\npersonal_account = <pages.personal_account_page.PersonalAccountPage object at 0x0000014F9C7E8C20>\ntest_user_create = <generator object test_user_create at 0x0000014F9C7B7300>\n\n    @allure.title(\"Тест: выход из аккаунта\")\n    def test_logout(self, driver, personal_account, test_user_create):\n        # Авторизация\n        test_user_create = test_user_create\n        print(\"sss\")\n>       print(test_user_create())\nE       TypeError: 'generator' object is not callable\n\ntests\\personal_account_test.py:44: TypeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"driver","time":{"start":1734771050352,"stop":1734771054956,"duration":4604},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"attachmentStep":false,"hasContent":false},{"name":"personal_account","time":{"start":1734771054956,"stop":1734771054957,"duration":1},"status":"passed","steps":[{"name":"Открытие главной страницы","time":{"start":1734771054957,"stop":1734771054957,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"driver","value":"<selenium.webdriver.chrome.webdriver.WebDriver (session=\"3cf13f068ec8a992cb22ee7148588ffd\")>"}],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"attachmentStep":false,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":1,"attachmentStep":false,"hasContent":true},{"name":"test_user_create","time":{"start":1734771054957,"stop":1734771054957,"duration":0},"status":"passed","steps":[{"name":"Создание пользователя через api","time":{"start":1734771054957,"stop":1734771054957,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"attachmentStep":false,"hasContent":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":1,"attachmentStep":false,"hasContent":true}],"testStage":{"status":"broken","statusMessage":"TypeError: 'generator' object is not callable","statusTrace":"self = <personal_account_test.TestRestorePassword object at 0x0000014F9C6EB490>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"3cf13f068ec8a992cb22ee7148588ffd\")>\npersonal_account = <pages.personal_account_page.PersonalAccountPage object at 0x0000014F9C7E8C20>\ntest_user_create = <generator object test_user_create at 0x0000014F9C7B7300>\n\n    @allure.title(\"Тест: выход из аккаунта\")\n    def test_logout(self, driver, personal_account, test_user_create):\n        # Авторизация\n        test_user_create = test_user_create\n        print(\"sss\")\n>       print(test_user_create())\nE       TypeError: 'generator' object is not callable\n\ntests\\personal_account_test.py:44: TypeError","steps":[],"attachments":[{"uid":"7075d86d03b9155b","name":"stdout","source":"7075d86d03b9155b.txt","type":"text/plain","size":4}],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":1,"stepsCount":0,"attachmentStep":false,"hasContent":true},"afterStages":[{"name":"driver::0","time":{"start":1734771055038,"stop":1734771057126,"duration":2088},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"attachmentStep":false,"hasContent":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('personal_account')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"personal_account_test"},{"name":"subSuite","value":"TestRestorePassword"},{"name":"host","value":"DESKTOP-7LU8FN0"},{"name":"thread","value":"5604-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.personal_account_test"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":["@pytest.mark.usefixtures('personal_account')"]},"source":"7d8a6e2433756b56.json","parameterValues":[]}